apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind.apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: kind
    namespace: argocd
  source:
    path: apps/clusters/kind
    repoURL: git@github.com:gkiranch/k8s-deployment
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true