config:
  # Set it to a valid URL
  issuer: http://dex.gk.guru.com

  # See https://dexidp.io/docs/storage/ for more options
  storage:
    type: memory

  # Enable at least one connector
  # See https://dexidp.io/docs/connectors/ for more options
  enablePasswordDB: true

ingress:
  enabled: true

  hosts:
    - host: dex.gk.guru.com
      paths:
        - path: /

  tls:
    - hosts:
        - dex.gk.guru.com
      secretName: dex-cert
