apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-world
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Hello World Example Deployments
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'hello-world'
      name: 'kind'