apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind.guestbook1
  namespace: argocd
spec:
  destination:
    namespace: guestbook-ns
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://github.com/gkiranch/k8s-deployment.git"
    targetRevision: HEAD
    path: manifests/guestbook1
  syncPolicy:
    syncOptions:
      - ServerSideApply=true