apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook.application
spec:
  destination:
    namespace: test-namespace
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://github.com/gkiranch/k8s-deployment.git"
    targetRevision: HEAD
    path: manifests/guestbook
  syncPolicy:
    syncOptions:
      - ServerSideApply=true