apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind.spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: s1-k8s-infra
  source:
    repoURL: "https://github.com/gkiranch/k8s-deployment.git"
    targetRevision: HEAD
    path: manifests/spark-operator/clusters/kind
  destination:
    name: in-cluster
    namespace: test-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true