apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: columbia.spark-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: s1-k8s-infra
  source:
    repoURL: git@ghe.eng.sentinelone.tech:Sentinel-One/k8s-deployments-infra
    targetRevision: HEAD
    path: manifests/k8s_infra/spark-operator/clusters/columbia
  destination:
    name: columbia
    namespace: spark-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true