apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.admin: apiKey, login
  url: https://argocd-lab.com
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      id: okta
      name: Okta
      config:
        ssoURL: https://dev-22392861.okta.com/app/dev-22392861_argocd_1/exkf34gnxtjuFz9Ma5d7/sso/saml
        # You need `caData` _OR_ `ca`, but not both.
        caData: |
          LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxRENDQXBDZ0F3SUJBZ0lHQVkyY0M2c3dNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1VNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUcNCkExVUVDQXdLUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnd3TlUyRnVJRVp5WVc1amFYTmpiekVOTUFzR0ExVUVDZ3dFVDJ0MFlURVUNCk1CSUdBMVVFQ3d3TFUxTlBVSEp2ZG1sa1pYSXhGVEFUQmdOVkJBTU1ER1JsZGkweU1qTTVNamcyTVRFY01Cb0dDU3FHU0liM0RRRUoNCkFSWU5hVzVtYjBCdmEzUmhMbU52YlRBZUZ3MHlOREF5TVRJd05qTTVNalphRncwek5EQXlNVEl3TmpRd01qWmFNSUdVTVFzd0NRWUQNClZRUUdFd0pWVXpFVE1CRUdBMVVFQ0F3S1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ3d05VMkZ1SUVaeVlXNWphWE5qYnpFTk1Bc0cNCkExVUVDZ3dFVDJ0MFlURVVNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RlRBVEJnTlZCQU1NREdSbGRpMHlNak01TWpnMk1URWMNCk1Cb0dDU3FHU0liM0RRRUpBUllOYVc1bWIwQnZhM1JoTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MNCmdnRUJBSy9qaHJqS0RYMU5jM0w4cVhoS1pub281MkZMWE14SWJsMzh3ZWlWWXozSDRRVS9hN3hvUHRzZ3ZIV0Z2T2w1QzNLaGhzMUoNClJyNlpqSHJrOHRSbnJia0JvaDZJR2tFSENiek5tSks1d1FsUEk2eVFUemY4ZkZsUyt5TUJIVm9IR1prTXRpMWpuZGx6VFF1aVdRT1cNCklCTUdTd081OEVLVkNiQm1EM05PdjJOdlRBaEt2Um12cS8rV0JUQnpIMnVac0NvQVFjeWNkZG1YbVdOenYxMFJoMTYwaGd0SlZyMWkNCmZ6b0FWVk9Rcmt5ZFdXcUlUcHY1dCtGZ1hkeGJ6aTdVbkwwZ0VQMXdUTmppYmlwanlPSGNReTNxVEZuRXYvTEE3UkZSTVRxNytTMGsNCjFscWpDVWNKOEpYNDhzcERkZGZPakx1T1I2dUUwRmJjV3FSUWlNekMxSXNDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUENCmdCaXEyZ0owOCs0YWIzd0w0dlMxUUt6ZUg4MEEraGFCM2FXQWRGVzkzNkx4ckVnSGxuVytYSmh1b0tiSUN6Zi8va0lrSmphS0FidkINClZrRTJYbzE4Q2VKWkhvTjM2YUxwNDdPdHNpajJOK1dTZ2hBcFl6VmV5WXFjZExVaDFmTjZYeTN3WmFISlZCNi9JWXJMblFydEFvTVYNCkc1VTFXd25pdUF6M1JGSlZNM1R0aXA5bWc1cUZLV01UVUdYTW1tWTJEOG96K0tmVml3NEd1Zy85SVdtNWpjUGFuQjNxNXI1N0NuQ1YNCmVqY0F3QUdZM2srK3IwUGJTUGZzdnRCS0QyaytrcFZ2UnZPNFdrdmRWdzl4MG9sRVRCbEpjSmRwMXVFZ3UyV09GT05ibWY5Nm56VEwNCjV4YjQyVHQ4Z2p5QmdwL1JZR3pTNDAzMlJlOFVmeFpVN2pRTkR3PT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        redirectURI: https://argocd-us.s1dev.cloud/api/dex/callback
        usernameAttr: email
        emailAttr: email
        groupsAttr: group
  accounts.readonly_user: apiKey,login
  accounts.ranger_admin: apiKey,login