apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.admin: apiKey, login
  url: https://localhost:8080
  dex.config: |
    logger:
      level: debug
      format: json
    connectors:
    - type: saml
      id: okta
      name: Okta
      config:
        ssoURL: https://dev-22392861.okta.com/app/dev-22392861_argocd_2/exkl0184zycgBmi5P5d7/sso/saml
        # You need `caData` _OR_ `ca`, but not both.
        caData: |
          LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxRENDQXBDZ0F3SUJBZ0lHQVpNUmdYNGdNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1VNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUcNCkExVUVDQXdLUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnd3TlUyRnVJRVp5WVc1amFYTmpiekVOTUFzR0ExVUVDZ3dFVDJ0MFlURVUNCk1CSUdBMVVFQ3d3TFUxTlBVSEp2ZG1sa1pYSXhGVEFUQmdOVkJBTU1ER1JsZGkweU1qTTVNamcyTVRFY01Cb0dDU3FHU0liM0RRRUoNCkFSWU5hVzVtYjBCdmEzUmhMbU52YlRBZUZ3MHlOREV4TURreE5URTNNemxhRncwek5ERXhNRGt4TlRFNE16bGFNSUdVTVFzd0NRWUQNClZRUUdFd0pWVXpFVE1CRUdBMVVFQ0F3S1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ3d05VMkZ1SUVaeVlXNWphWE5qYnpFTk1Bc0cNCkExVUVDZ3dFVDJ0MFlURVVNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RlRBVEJnTlZCQU1NREdSbGRpMHlNak01TWpnMk1URWMNCk1Cb0dDU3FHU0liM0RRRUpBUllOYVc1bWIwQnZhM1JoTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MNCmdnRUJBTVpoM1Y3ckdsTGdmOEIyM0V4cGtzZUJxVTV5aVZ5QWhkUnNIeXhNUE5mTUI4SE1HUUxnTy83K0RhZ1RvcWpOOUttK2NFYmwNCnZ4QmxCY0d4UFlZd2Zvdit3dUs1TWRZQUwwY1R5dnJMRHQ3dHpvSnFZS1ErdXJkWm5QaVFPbktjU3Jwb3BRSjVUeHV2Qjh2ejVWcmMNClp3TFVERjFTaWphdkJkQ3RtaUxXNEhZWStWTzJWZE9LZ21IaTJHWFBrZHFENDNhdEJoOExQVExtZlNQcmgzZjJhR1AxWE90dlJxc3UNClh1ZnE5WGlTazA0UzRYeTZycmsyYmxHTWhyeW9KR1BGUkNIcGxQbVRoZnQzV20rbUZKUTlFMllUc3N1dTliQzBVODZQQ3RVTTIyMXINClpwc21KR3RDaTYwdHVaTFdzV0ZQdDh3VXBxQ3ltbDNweVZLaEVGZ0g5Z2NDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUENCnFMMkRUTmJRbklhWUVnMFlSdTFGdm5BTXJNTFZkMDRZbFp1U2pMNjRVMnlWSGhlaWNFLzVEMzM3YjBSK0RMWm9FRlNiRWN4ZUN1MFUNCkhyTlpUeXVSTElnNXBsV1UxZ05KZThhaFVxQk4zM1ExemlSRFBtOE1KRzUyeGNNNGgrOGJzN2tKWjdWUmdpT3g1Tkh6V0dCOVRoZm0NCnFpODM1RkI4K3A0eWVwMVhZR3FwdFZkby80WjdHd1BGYURWbkV2SGpzSFBXdnNvOS9vdWxMZVJoRG5UQU1laWxlSC9TQ21JcWFVRC8NClpZREF0YndyQm5VYVRMMnpiNnlpbW96TGVGSEU2S2ZTMzRuSFovT3ZFY01SdTB2blRWSlRza2RDcm96R2d3MVlvVVlPeVR5ZFU1eGcNCmRiNDdIRzd5TG45YlZUNjFYWUkyUFdjS1prdU1nM3lveWJjRmhRPT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        redirectURI: https://localhost:8080/api/dex/callback
        usernameAttr: email
        emailAttr: email
        groupsAttr: group
  accounts.readonly_user: apiKey,login
  accounts.ranger_admin: apiKey,login