apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: app-of-apps/clusters/kind
    repoURL: git@github.com:gkiranch/k8s-deployment
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true