apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind.secure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:gkiranch/k8s-deployment
    targetRevision: HEAD
    path: secure/clusters/kind
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
