apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind.secure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/gkiranch/k8s-deployment.git"
    targetRevision: HEAD
    path: secure/base
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
