apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: v1
kind: Namespace
metadata:
  name: guestbooknew
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace

---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: guestbook-ns