name: Custom Build and Push

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'release/*'

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensure sufficient depth for commit history

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/kustomize

      - name: Check for changes in 'apps' and 'secure' directories
        id: check_changes
        run: |
          git fetch --depth=2 || exit 0  # Fetch the commit history with sufficient depth
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} || echo "")

          echo "Changed files: $CHANGED_FILES"

          APPS_CHANGED=$(echo "$CHANGED_FILES" | grep '^k8s-deployment/k8s-deployment/apps/' || echo "")
          SECURE_CHANGED=$(echo "$CHANGED_FILES" | grep '^secure/' || echo "")

          if [ -n "$APPS_CHANGED" ]; then
            echo "Files in 'apps' have been changed."
            echo "::set-output name=apps_changed::true"
          else
            echo "No changes in 'apps'."
            echo "::set-output name=apps_changed::false"
          fi

          if [ -n "$SECURE_CHANGED" ]; then
            echo "Files in 'secure' have been changed."
            echo "::set-output name=secure_changed::true"
          else
            echo "No changes in 'secure'."
            echo "::set-output name=secure_changed::false"
          fi

      - name: Run kustomize build for each cluster in 'apps/clusters'
        if: steps.check_changes.outputs.apps_changed == 'true'
        run: |
          echo "Running kustomize build for each cluster in 'apps/clusters'..."
          for dir in k8s-deployment/k8s-deployment/apps/clusters/*; do
            if [ -d "$dir" ]; then
              CHANGED_FILES_IN_DIR=$(echo "$CHANGED_FILES" | grep "^${dir#*/}" || echo "")
              if [ -n "$CHANGED_FILES_IN_DIR" ]; then
                echo "Processing directory $dir"
                cd $dir
                kustomize build .
                cd -  # Go back to previous directory
              fi
            fi
          done
          echo "kustomize build for all clusters in 'apps/clusters' completed."

      - name: Run kustomize build for 'secure'
        if: steps.check_changes.outputs.secure_changed == 'true'
        run: |
          echo "Running kustomize build for 'secure'..."
          cd secure
          kustomize build .
          echo "kustomize build for 'secure' completed."

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.apps_changed == 'true' || steps.check_changes.outputs.secure_changed == 'true'
        env:
          NEW_GITHUB_TOKEN: ${{ secrets.NEW_GITHUB_TOKEN }}
        run: |
          git add -A
          git commit -m "Automated commit for changes in apps/clusters or secure directory"
          git push "https://${NEW_GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}

      - name: No relevant changes detected
        if: steps.check_changes.outputs.apps_changed == 'false' && steps.check_changes.outputs.secure_changed == 'false'
        run: echo "No relevant changes detected in 'apps' or 'secure' directories."
